(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['aboutTemp'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"container main-padding\">\r\n    <div class=\"row rows-padding\">\r\n        <div class=\"col-md-6 about-cells-2   elements-margin \">\r\n            <p class=\"text-style\">\r\n                <strong class=\"main-words\">Ретвитни оброк</strong> е иницијатива (формирана на Твитер) на аматери готвачи\r\n                кои сакаат да споделуваат храна, не само на Интернет. <br/>\r\n\r\n            </p>\r\n        </div>\r\n        <div class=\"col-md-3 about-img-1 elements-margin \">\r\n            <img src=\"img/about/2.png\" class=\"img-circle about-img-1\">\r\n        </div>\r\n        <div class=\"col-md-3 about-img-1 elements-margin \">\r\n            <img src=\"img/about/4.png\" class=\"img-circle about-img-1\">\r\n        </div>\r\n    </div>\r\n    <div class=\"row rows-padding\">\r\n        <div class=\"col-md-3 about-img-1 elements-margin \">\r\n            <img src=\"img/about/1.png\" class=\"img-circle about-img-1\">\r\n        </div>\r\n        <div class=\"col-md-3 about-img-1 elements-margin \">\r\n            <img src=\"img/about/5.png\" class=\"img-circle about-img-1\">\r\n        </div>\r\n        <div class=\"col-md-6 about-cells-2 elements-margin \">\r\n            <p class=\"text-style\">\r\n                <strong class=\"main-words\">Што сакаме да направиме?</strong><br/> Да ја подигнеме свеста на луѓето и да стигнеме до момент храната која останува при готвење\r\n                да не се фрла, туку да се споделува со оние кои немаат.\r\n            </p>\r\n        </div>\r\n    </div>\r\n    <div class=\"row rows-padding\">\r\n        <div class=\"col-md-3 about-cells-1 elements-margin \">\r\n            <p class=\"text-style\">\r\n                <strong class=\"main-words\">Локација</strong>: Пред спомен-куќата на Мајка Тереза. <br/>\r\n                <strong class=\"main-words\">Ден</strong>: Секоја сабота. <br/>\r\n                <strong class=\"main-words\">Време</strong>: 13:00  <br/>\r\n            </p>\r\n        </div>\r\n        <div class=\"col-md-3 about-cells-1 elements-margin \">\r\n            <p class=\"text-style-last\">\r\n                <strong class=\"main-words\">37</strong> недели готвење.<br/>\r\n                <strong class=\"main-words\">110</strong> оброци неделно.<br/>\r\n                До сега <strong class=\"main-words\">4070</strong> споделени оброци.\r\n            </p>\r\n        </div>\r\n        <div class=\"col-md-3 about-img-1 elements-margin \">\r\n            <img src=\"img/about/3.png\" class=\"img-circle about-img-1\">\r\n        </div>\r\n        <div class=\"col-md-3 about-img-1 elements-margin \">\r\n            <img src=\"img/about/6.png\" class=\"img-circle about-img-1\">\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n";
},"useData":true});
templates['calendarTemp'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "";
},"useData":true});
templates['contactTemp'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "\r\n<h1>Ova mi e contact</h1>\r\n";
},"useData":true});
templates['galleryTemp'] = template({"1":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "        <figure>\r\n            <img src=\""
    + alias4(((helper = (helper = helpers.src || (depth0 != null ? depth0.src : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"src","hash":{},"data":data}) : helper)))
    + "\">\r\n            <figcaption>"
    + alias4(((helper = (helper = helpers.text || (depth0 != null ? depth0.text : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"text","hash":{},"data":data}) : helper)))
    + "</figcaption>\r\n        </figure>\r\n";
},"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, options, buffer = 
  "<div id=\"columns\">\r\n\r\n";
  stack1 = ((helper = (helper = helpers.images || (depth0 != null ? depth0.images : depth0)) != null ? helper : helpers.helperMissing),(options={"name":"images","hash":{},"fn":container.program(1, data, 0),"inverse":container.noop,"data":data}),(typeof helper === "function" ? helper.call(depth0 != null ? depth0 : {},options) : helper));
  if (!helpers.images) { stack1 = helpers.blockHelperMissing.call(depth0,stack1,options)}
  if (stack1 != null) { buffer += stack1; }
  return buffer + "</div>";
},"useData":true});
templates['homeTemp'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    return "<div class=\"row\">\r\n<img src=\"img/background1.png\" class=\"main-img\">\r\n    <div class=\"buttons-group\">\r\n      <div class=\"btn-postion\">\r\n        <button class=\"btn btns-style doniraj-btn\">ДОНИРАЈ</button>\r\n      </div>\r\n      <div>\r\n         <button class=\"btn btns-style zgotvi-btn\">ЗГОТВИ</button>\r\n      </div>\r\n    </div>\r\n</div>\r\n<div class=\"row row-position\">\r\n    <div class=\"col-md-4 steps-title-style\">\r\n         Како функционираме?\r\n    </div>\r\n</div>\r\n<div class=\"row imgs-pos\">\r\n        <div class=\"col-md-2\">\r\n            <img src=\"img/steps/1.png\" class=\"img-steps-style\" >\r\n            <p class=\"step-txt\">Пријави се</p>\r\n        </div>\r\n        <div class=\"col-md-2\">\r\n            <img src=\"img/steps/2.png\" class=\"img-steps-style\" >\r\n            <p class=\"step-txt\">Подготви ги намирниците</p>\r\n        </div>\r\n        <div class=\"col-md-2\">\r\n            <img src=\"img/steps/3.png\" class=\"img-steps-style\" >\r\n            <p class=\"step-txt\">Донирај</p>\r\n        </div>\r\n        <div class=\"col-md-2\">\r\n            <img src=\"img/steps/4.png\" class=\"img-steps-style\" >\r\n            <p class=\"step-txt\">Зготви</p>\r\n        </div>\r\n        <div class=\"col-md-2\">\r\n            <img src=\"img/steps/5.png\" class=\"img-steps-style\" >\r\n            <p class=\"step-txt\">Сподели оброк</p>\r\n        </div>\r\n    </div>";
},"useData":true});
})();